# =============================================================================
# FILE: generate_env_key.py
# PURPOSE: One-time script to generate a secure AES key and write to .env
# RUN ONCE: python generate_env_key.py
# =============================================================================

import os
import secrets
from cryptography.fernet import Fernet

ENV_FILE = ".env"

def generate_env():
    print("🔑 Generating secure keys for your .env file...\n")

    # Generate AES-256 key
    aes_key = Fernet.generate_key().decode("utf-8")

    # Generate a strong JWT secret (32 random bytes = 256 bits)
    jwt_secret = secrets.token_hex(32)

    env_content = f"""# ============================================================
# .env — Secret Keys for Secure Data Vault
# ============================================================
# NEVER commit this file to Git. Add .env to your .gitignore!
# ============================================================

# AES-256 Key (generated by cryptography.Fernet)
# Used to encrypt/decrypt all user notes at rest
AES_KEY={aes_key}

# JWT Secret Key (used to sign authentication tokens)
# Must be long and random — never share or hardcode
JWT_SECRET={jwt_secret}
"""

    if os.path.exists(ENV_FILE):
        print(f"⚠️  {ENV_FILE} already exists!")
        confirm = input("   Overwrite it? (yes/no): ").strip().lower()
        if confirm != "yes":
            print("   Cancelled. Existing .env was not changed.")
            return

    with open(ENV_FILE, "w") as f:
        f.write(env_content)

    # Set file permissions to owner-read-only (Linux/Mac)
    # This prevents other users on the system from reading your keys
    os.chmod(ENV_FILE, 0o600)

    print(f"✅ .env created successfully with secure keys.")
    print(f"   File permissions set to 600 (owner read/write only).")
    print(f"\n   AES Key  : {aes_key[:20]}...  (truncated for display)")
    print(f"   JWT Secret: {jwt_secret[:20]}...  (truncated for display)")
    print(f"\n⚠️  Add .env to your .gitignore immediately!")

if __name__ == "__main__":
    generate_env()
